<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="2" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-03-19T17:14:20 IST" name="Default suite" finished-at="2021-03-19T17:14:55 IST" duration-ms="34777">
    <groups>
    </groups>
    <test started-at="2021-03-19T17:14:20 IST" name="Default test" finished-at="2021-03-19T17:14:55 IST" duration-ms="34777">
      <class name="com.registrationtest.RambollRegistrationTest1">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.registrationtest.RambollRegistrationTest1@20d28811]" started-at="2021-03-19T17:14:20 IST" name="setUp" finished-at="2021-03-19T17:14:22 IST" duration-ms="1992" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="completeRegisteration()[pri:0, instance:com.registrationtest.RambollRegistrationTest1@20d28811]" started-at="2021-03-19T17:14:22 IST" name="completeRegisteration" finished-at="2021-03-19T17:14:31 IST" duration-ms="8673" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- completeRegisteration -->
        <test-method is-config="true" signature="cleanUp()[pri:0, instance:com.registrationtest.RambollRegistrationTest1@20d28811]" started-at="2021-03-19T17:14:31 IST" name="cleanUp" finished-at="2021-03-19T17:14:32 IST" duration-ms="1408" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanUp -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.registrationtest.RambollRegistrationTest1@20d28811]" started-at="2021-03-19T17:14:32 IST" name="setUp" finished-at="2021-03-19T17:14:33 IST" duration-ms="947" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="emailFormat()[pri:0, instance:com.registrationtest.RambollRegistrationTest1@20d28811]" started-at="2021-03-19T17:14:33 IST" name="emailFormat" finished-at="2021-03-19T17:14:35 IST" duration-ms="1815" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Provide valid Email address]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Provide valid Email address
at com.registrationtest.RambollRegistrationTest1.emailFormat(RambollRegistrationTest1.java:69)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- emailFormat -->
        <test-method is-config="true" signature="cleanUp()[pri:0, instance:com.registrationtest.RambollRegistrationTest1@20d28811]" started-at="2021-03-19T17:14:35 IST" name="cleanUp" finished-at="2021-03-19T17:14:35 IST" duration-ms="182" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanUp -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.registrationtest.RambollRegistrationTest1@20d28811]" started-at="2021-03-19T17:14:35 IST" name="setUp" finished-at="2021-03-19T17:14:36 IST" duration-ms="942" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="passwordCheck()[pri:0, instance:com.registrationtest.RambollRegistrationTest1@20d28811]" started-at="2021-03-19T17:14:36 IST" name="passwordCheck" finished-at="2021-03-19T17:14:50 IST" duration-ms="14465" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- passwordCheck -->
        <test-method is-config="true" signature="cleanUp()[pri:0, instance:com.registrationtest.RambollRegistrationTest1@20d28811]" started-at="2021-03-19T17:14:50 IST" name="cleanUp" finished-at="2021-03-19T17:14:51 IST" duration-ms="169" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanUp -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.registrationtest.RambollRegistrationTest1@20d28811]" started-at="2021-03-19T17:14:51 IST" name="setUp" finished-at="2021-03-19T17:14:52 IST" duration-ms="900" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="resetBtnChk()[pri:0, instance:com.registrationtest.RambollRegistrationTest1@20d28811]" started-at="2021-03-19T17:14:52 IST" name="resetBtnChk" finished-at="2021-03-19T17:14:53 IST" duration-ms="1213" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Reset button is not working]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Reset button is not working
at com.registrationtest.RambollRegistrationTest1.resetBtnChk(RambollRegistrationTest1.java:80)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resetBtnChk -->
        <test-method is-config="true" signature="cleanUp()[pri:0, instance:com.registrationtest.RambollRegistrationTest1@20d28811]" started-at="2021-03-19T17:14:53 IST" name="cleanUp" finished-at="2021-03-19T17:14:53 IST" duration-ms="144" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanUp -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.registrationtest.RambollRegistrationTest1@20d28811]" started-at="2021-03-19T17:14:53 IST" name="setUp" finished-at="2021-03-19T17:14:54 IST" duration-ms="889" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="validationCheck()[pri:0, instance:com.registrationtest.RambollRegistrationTest1@20d28811]" started-at="2021-03-19T17:14:54 IST" name="validationCheck" finished-at="2021-03-19T17:14:55 IST" duration-ms="762" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Email Id not provided]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Email Id not provided
at com.registrationtest.RambollRegistrationTest1.validationCheck(RambollRegistrationTest1.java:60)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validationCheck -->
        <test-method is-config="true" signature="cleanUp()[pri:0, instance:com.registrationtest.RambollRegistrationTest1@20d28811]" started-at="2021-03-19T17:14:55 IST" name="cleanUp" finished-at="2021-03-19T17:14:55 IST" duration-ms="171" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanUp -->
      </class> <!-- com.registrationtest.RambollRegistrationTest1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
